run:
  concurrency: 4
  timeout: 5m
  issues-exit-code: 1
  tests: true
  issues:
    exclude-files:
      - \.pb\.go$
      - \.pb\.gw\.go$
    exclude-dirs:
      - bin
      - vendor
      - var
      - tmp
      - .cache
      - .git
      - .github

output:
  formats: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  govet:
    shadow: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2

linters:
  disable-all: true
  enable:
    - errcheck
    - goimports
    - govet
    - typecheck

issues:
  exclude-use-default: false
  exclude:
    - G104 # _ instead of err checks
    - exported func .* returns unexported type .*, which can be annoying to use
    - should have a package comment
    - don't use an underscore in package name