version: "1.0"

run:
  timeout: 2m
  tests: true

linters:
  enable:
    - govet         # Проверка на потенциальные ошибки компиляции и поведения
    - staticcheck   # Глубокий анализ, находит баги, устаревшие конструкции, бессмысленный код
    - errcheck      # Находит необработанные ошибки
    - ineffassign   # Обнаруживает неэффективные присваивания
    - gosimple      # Советы по упрощению кода
    - unused        # Находит неиспользуемый код
    - structcheck   # Проверяет, что все поля структур реально используются
    - gofmt         # Проверка форматирования кода (аналог go fmt)
    - goimports     # Проверка на порядок и использование импортов
    - goconst       # Предлагает выносить повторяющиеся строковые/числовые значения в `const`

  exclusions:
    generated: lax            # Игнорировать строго сгенерированные файлы
    warn-unused: true
    presets:
      - comments
      - std-error-handling
      - common-false-positives
      - legacy
    paths:
      - ".*_gen\\.go$"        # Дополнительно игнорировать файлы с таким суффиксом

issues:
  max-issues-per-linter: 0  # Нет лимита по количеству ошибок от одного линтера
  max-same-issues: 0        # Нет лимита по количеству одинаковых ошибок
